### ISSUE TITLE
Feature request: Create a docker container

### ISSUE THREAD

**Issue by torwag** [mhthies/ews-caldav-sync#1]
Hi,
nice project.... this seems to ask for a docker container to run it as a self-hosted service, maybe along the Nextcloud container.

**Comment by mhthies** [comment]
To be honest, I'm a bit oldschool and do not use Docker (or any related container technology) in my private webhosting environments. Thus, I'm not really familiar with best practices for packaging such an application into a docker image, esp. considering configuration file handling and cron job invocation.

However, I see that this would be a nice addition. So, feel free to create a Dockerfile and open a PR to add it to this repository! :)

**Comment by emorozov** [comment]
Hey @torwag,
Added basic Dockerfile here https://github.com/mhthies/ews-caldav-sync/pull/4

**Comment by mhthies** [comment]
Fixed by #4.
Many thanks to @emorozov, again! :)
